# Schema for the views style plugins.

views.style.gliderjs:
  type: views_style
  label: 'Gliderjs'
  mapping:
    slides_to_show:
      type: string
      label: 'The number of slides to show in container.'
    slides_to_scroll:
      type: string
      label: 'The number of slides to scroll when arrow navigation is used.'
    show_arrows:
      type: boolean
      label: 'Show Arrows.'
    show_dots:
      type: boolean
      label: 'Show Dots.'
    item_width:
      type: integer
      label: 'The item width.'
    exact_width:
      type: boolean
      label: 'Use exact item width.'
    scroll_lock:
      type: boolean
      label: 'If checked, it will scroll to the nearest slide after any scroll interactions.'
    scroll_lock_delay:
      type: integer
      label: 'The delay in milliseconds to wait before the scroll happens.'
    resize_lock:
      type: boolean
      label: 'If checked, the nearest slide on resizing of the window will be locked.'
    rewind:
      type: boolean
      label: 'If checked, it will scroll to the beginning/end when its respective endpoint is reached.'
    draggable:
      type: boolean
      label: 'If checked, the list can be scrolled by click and dragging with the mouse.'
    drag_velocity:
      type: float
      label: 'How much to aggravate the velocity of the mouse dragging.'
    duration:
      type: float
      label: 'An aggravator used to control animation speed. Higher is slower!'
    scroll_propagate:
      type: boolean
      label: 'Whether or not to release the scroll events from the container.'
    event_propagate:
      type: boolean
      label: 'Whether or not Glider.js events should bubble (useful for binding events to all sliders).'
    skip_track:
      type: boolean
      label: 'Whether or not Glider.js should skip wrapping its children with a "glider-track" <div>.'
    breakpoint_settings:
      type: mapping
      label: 'Breakpoint Settings.'
      mapping:
        slides_to_show:
          type: string
          label: 'The number of slides to show in container.'
        slides_to_scroll:
          type: string
          label: 'The number of slides to scroll when arrow navigation is used.'
        show_arrows:
          type: boolean
          label: 'Show Arrows.'
        show_dots:
          type: boolean
          label: 'Show Dots.'
        item_width:
          type: integer
          label: 'The item width.'
        exact_width:
          type: boolean
          label: 'Use exact item width.'
        scroll_lock:
          type: boolean
          label: 'If checked, it will scroll to the nearest slide after any scroll interactions.'
        scroll_lock_delay:
          type: integer
          label: 'The delay in milliseconds to wait before the scroll happens.'
        resize_lock:
          type: boolean
          label: 'If checked, the nearest slide on resizing of the window will be locked.'
        rewind:
          type: boolean
          label: 'If checked, it will scroll to the beginning/end when its respective endpoint is reached.'
        draggable:
          type: boolean
          label: 'If checked, the list can be scrolled by click and dragging with the mouse.'
        drag_velocity:
          type: float
          label: 'How much to aggravate the velocity of the mouse dragging.'
        duration:
          type: float
          label: 'An aggravator used to control animation speed. Higher is slower!'
        scroll_propagate:
          type: boolean
          label: 'Whether or not to release the scroll events from the container.'
        event_propagate:
          type: boolean
          label: 'Whether or not Glider.js events should bubble (useful for binding events to all sliders).'
        skip_track:
          type: boolean
          label: 'Whether or not Glider.js should skip wrapping its children with a "glider-track" <div>.'
